### ISSUE TITLE
Python doesn't recognise the "Imset" class

### ISSUE THREAD

**Issue by ApexBurger** [ApexBurger/crosspy#13]
This is a problem in the class definition of DIC where the __init__ has an if condition to determine if the input images are Imset or numpy arrays - Imset is used to instatiate and pull images whereas the numpy arrays are output from the correction algorithm (for then to be placed in a second pass instatiation.

**Comment by tmcaul** [comment]
fixed and pushed to master - now checks for crosspy.Imset as well as the Imset that is defined directly above.

https://github.com/ApexBurger/crosspy/commit/8ea6e28488363c4bb82094286293933f563d4029

**Comment by tmcaul** [comment]
can you test and then we can mark as closed?
